### signup a user
POST http://localhost:3000/auth/signup
Content-Type: application/json

  {
    "email": "user@email.com",
    "password": "1234"
  }

### login a user
POST http://localhost:3000/auth/login
Content-Type: application/json

  {
    "email": "user@email.com",
    "password": "1234"
  }

###  Authinticate a user
GET http://localhost:3000/auth/authenticate
Authorization: yourJwtHere

### Fetch all posts
GET http://localhost:3000/posts

### Delete all posts
DELETE http://localhost:3000/posts

### Add a post
POST http://localhost:3000/posts/add
Content-Type: application/json

  {
      "timestamp": "2024-12-03 14:30:00",
      "text": "This is a TEST!"
  }

